version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    expose:
      - '8000'
    depends_on:
      database:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:alpine

  database:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: rest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"

  celery:
    build:
      context: ./
      dockerfile: Dockerfile.celery
    depends_on:
      - rabbitmq
  