FROM python:3.10-slim

WORKDIR /taskpikasso

ADD ./ /taskpikasso/

RUN apt-get update \
    && apt-get -y install libpq-dev python-dev-is-python3 gcc

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

EXPOSE 8000
WORKDIR /taskpikasso/app
CMD celery -A app worker -l info --pool=solo